name: Discord Branch Notification

on:
  create: 

jobs:
  notify:
    if: github.event.ref_type == 'branch' 
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Message
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: success 
          nodetail: true
          noprefix: true
          title: "🚀 有新分支上線囉！"
          description: |
            👤 誰推的: `${{ github.actor }}`
            🌿 哪個分支: `${{ github.ref_name }}`
          color: 0x3498db 