name: Deploy to GitHub Pages

on:
  push:
    branches:
      - chore/deploy-workflows
  workflow_dispatch: # 允許手動點擊按鈕部署，以便除錯

permissions:
  contents: read
  pages: write
  id-token: write

# 避免多個部署任務同時進行導致衝突
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # 任務 1：打包
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        # 未來若有 API，需新增 env 區塊

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      - name: Discord Notification (Build)
        if: always()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          nodetail: true # 隱藏預設的複雜表格與連結
          noprefix: true # 隱藏預設的 "Success:" 或 "Failure:" 英文前綴
          # 利用判斷式自動切換 Icon 與文字
          title: "${{ job.status == 'success' && '✅ 打包成功' || '❌ 打包失敗' }}"
          description: |
            👤 **部署人員:** `${{ github.actor }}`
            🌿 **部署分支:** `${{ github.ref_name }}`

  # 任務 2：部署
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build # 確保 build 成功後才執行部署
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Discord Notification （Deploy Job）
        if: always()
        # 確保無論部署成功或失敗，這一步都會執行
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          nodetail: true # 隱藏預設的複雜表格與連結
          noprefix: true # 隱藏預設的 "Success:" 或 "Failure:" 英文前綴
          # 利用判斷式自動切換 Icon 與文字
          title: "${{ job.status == 'success' && '✅ 部署成功' || '❌ 部署失敗' }}"
          description: |
            👤 **部署人員:** `${{ github.actor }}`
            🌿 **部署分支:** `${{ github.ref_name }}`
            🔗 **部署網址:** `${{ steps.deployment.outputs.page_url }}`
